"use client";
import { useCallback, useState } from "react";
import { MovieGrid } from "@/components/movies/MovieGrid";
import { Pagination } from "@/components/pagination/Pagination";
import { SearchBar } from "@/components/search/SearchBar";
import { EmptyState } from "@/components/states/EmptyState";
import { ErrorState } from "@/components/states/ErrorState";
import { LoadingState } from "@/components/states/LoadingState";
import { useMovies } from "@/features/movies/queries";
export default function Home() { const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const onSearch = useCallback((value: string) => { setSearch(value); setPage(1); }, []); const { data, isPending, isError, error, refetch, isFetching } = useMovies(page, search); return <main><section className="relative overflow-hidden border-b border-white/10 bg-[radial-gradient(circle_at_70%_10%,rgba(229,183,102,.2),transparent_30%),linear-gradient(120deg,#171719,#09090b)]"><div className="mx-auto max-w-7xl px-5 py-20 sm:py-28"><p className="text-sm font-medium tracking-[0.22em] text-gold">CURATED FOR TONIGHT</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">A better way to find what moves you.</h1><p className="mt-5 max-w-xl text-zinc-400">Explore the films everyone is talking about, or follow a title wherever your curiosity leads.</p><div className="mt-9 max-w-2xl"><SearchBar onSearch={onSearch} /></div></div></section><section className="mx-auto max-w-7xl px-5 py-12"><div className="mb-8 flex items-end justify-between"><div><p className="text-sm text-gold">{search ? "Search results" : "Now showing"}</p><h2 className="mt-1 text-2xl font-semibold">{search ? `Results for “${search}”` : "Popular right now"}</h2></div>{isFetching && !isPending ? <span className="text-sm text-zinc-500">Updating…</span> : null}</div>{isPending ? <LoadingState /> : isError ? <ErrorState message={error instanceof Error ? error.message : "Something went wrong."} onRetry={() => void refetch()} /> : data && data.results.length ? <><MovieGrid movies={data.results} /><Pagination page={page} totalPages={data.totalPages} onPageChange={setPage} /></> : <EmptyState title="Nothing found in this reel" detail="Try a different title or browse today’s popular films." />}</section></main>; }
