"use client";
import Image from "next/image";
import Link from "next/link";
import { FavoriteButton } from "@/components/movies/FavoriteButton";
import { ErrorState } from "@/components/states/ErrorState";
import { Skeleton } from "@/components/ui/Skeleton";
import { useMovie } from "@/features/movies/queries";
import { formatRuntime, imageUrl } from "@/lib/utils";
export function MovieDetails({ id }: { id: string }) { const { data: movie, isPending, isError, error, refetch } = useMovie(id); if (isPending) return <div className="mx-auto max-w-7xl px-5 py-12"><Skeleton className="h-[420px] w-full" /></div>; if (isError || !movie) return <main className="mx-auto max-w-3xl px-5 py-16"><ErrorState message={error instanceof Error ? error.message : "Movie unavailable."} onRetry={() => void refetch()} /></main>; return <main><section className="relative isolate min-h-[540px] overflow-hidden"><Image src={imageUrl(movie.backdropPath, "original")} alt="" fill priority className="-z-20 object-cover opacity-45" /><div className="absolute inset-0 -z-10 bg-gradient-to-t from-ink via-ink/65 to-ink/20" /><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 pb-12 pt-12 sm:flex-row sm:items-end sm:pt-40"><Image src={imageUrl(movie.posterPath)} alt={`${movie.title} poster`} width={220} height={330} className="hidden rounded-xl border border-white/15 shadow-2xl sm:block" /><div className="max-w-2xl"><Link href="/" className="text-sm text-gold hover:text-amber-200">â† Back to discovery</Link><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-6xl">{movie.title}</h1><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-sm text-zinc-300"><span>{movie.releaseDate ?? "Release date unavailable"}</span><span className="text-gold">â˜… {movie.rating.toFixed(1)}</span><span>{formatRuntime(movie.runtime)}</span></div><div className="mt-5 flex flex-wrap gap-2">{movie.genres.map(genre => <span key={genre.id} className="rounded-full border border-white/15 px-3 py-1 text-xs text-zinc-300">{genre.name}</span>)}</div><p className="mt-6 text-base leading-7 text-zinc-300">{movie.overview || "No overview is available for this title."}</p><div className="mt-7"><FavoriteButton movie={movie} /></div></div></div></section></main>; }
